analytics:
  google: UA-47003751-1
color:
  brandColors: []
  brandStrength: 0
  lightness: 0.622747
  rhythmicContrast: 0.199324
  saturation: 0
cta: {}
layout_spectrum: 0.139639
name: BenjaminBlue
opengraph: {}
purpose: []
typography_spectrum: 1
