analytics:
  google: UA-72243025-1
color:
  brandColors:
    - '#C0E0D8'
    - '#003058'
    - '#608898'
    - '#008BFF'
    - '#000000'
  brandStrength: 0.71509
  lightness: 0.568693
  rhythmicContrast: 0.373873
  saturation: 0.495495
cta: {}
layout_spectrum: 0.013513
name: BenjaminBlue
opengraph: {}
purpose: []
typography_spectrum: 1
