name: BenjaminBlue
favicon: null
layout_spectrum: 0.18581
typography_spectrum: 1
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-47003751-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.25
  lightness: 0.4375
  saturation: 0.625
  rhythmicContrast: 0.75
purpose: []
