analytics:
  google: UA-47003751-1
color:
  brandColors: []
  brandStrength: 0
  lightness: 0.427927
  rhythmicContrast: 0
  saturation: 0
cta: {}
layout_spectrum: 0.425675
name: BenjaminBlue
opengraph: {}
purpose: []
typography_spectrum: 1
