analytics:
  google: UA-47003751-1
color:
  brandColors: []
  brandStrength: 0
  lightness: 0.747959
  rhythmicContrast: 0.662162
  saturation: 0.347854
cta: {}
layout_spectrum: 0.7526
name: BenjaminBlue
opengraph: {}
purpose: []
typography_spectrum: 0.814189
