name: BenjaminBlue
favicon: null
layout_spectrum: 0.75186
typography_spectrum: 1
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-72243025-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#C0E0D8'
    - '#003058'
    - '#608898'
    - '#008BFF'
    - '#000000'
  brandStrength: 0.4375
  lightness: 0.5625
  saturation: 0.412313
  rhythmicContrast: 0.196828
purpose: []
