analytics:
  google: UA-72243025-1
color:
  brandColors:
    - '#C0E0D8'
    - '#003058'
    - '#608898'
    - '#008BFF'
    - '#000000'
  brandStrength: 0.4375
  lightness: 0.5625
  rhythmicContrast: 0.196828
  saturation: 0.412313
cta: {}
layout_spectrum: 0.47562
name: BenjaminBlue
opengraph: {}
purpose: []
typography_spectrum: 1
