layout_spectrum: 0.45651
typography_spectrum: 0.7802563218865544
color:
  brandColors:
    - '#225378'
    - '#1695A3'
    - '#ACF0F2'
    - '#F3FFE2'
    - '#EB7F00'
  brandStrength: 0.7976047864649445
  lightness: 0.8013522790279239
  saturation: 0.4846620911266655
  rhythmicContrast: 0.45380753348581493
opengraph:
  image: null
  type: null
  appId: null
analytics:
  google: UA-72243025-1
  facebook: null
  twitter: null
name: The World Of Blue
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - url: 'http://blog.benjaminblue.me'
    name: Blog
    type: external
  - url: 'http://photography.benjaminblue.me'
    name: Photography
    type: external
  - url: 'http://levelb.benjaminblue.me'
    name: Game Design
    type: external
favicon: null
title: The World Of Blue
purpose: []
