name: BenjaminBlue
favicon: null
layout_spectrum: 0.256756
typography_spectrum: 1
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-72243025-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#C8B088'
    - '#000028'
    - '#A86058'
    - '#C06870'
    - '#E0E0A8'
  brandStrength: 0.354729
  lightness: 0.57545
  saturation: 0
  rhythmicContrast: 0
purpose: []
