typography_spectrum: 1
color:
  brandColors:
    - '#c4cdd4'
    - '#71828c'
    - '#191e24'
    - '#9dabb4'
    - '#424e5a'
  brandStrength: 0.1875
  lightness: 0.5625
  saturation: 0.25
  rhythmicContrast: 0.5
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.45651
analytics:
  google: UA-72243025-1
  facebook: null
  twitter: null
name: The World Of Blue
cta:
  domain: null
  bucket: null
  version: null
navigation: []
favicon: null
title: The World Of Blue
purpose: []
