name: BenjaminBlue
favicon: null
layout_spectrum: 0
typography_spectrum: 0.14993
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-72243025-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#C0E0D8'
    - '#003058'
    - '#608898'
    - '#008BFF'
    - '#000000'
  brandStrength: 1
  lightness: 0.375
  saturation: 0.3125
  rhythmicContrast: 0.75
purpose: []
