name: BenjaminBlue
favicon: null
layout_spectrum: 0.53877
typography_spectrum: 0.97203
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-47003751-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0
  lightness: 0.375
  saturation: 0.75
  rhythmicContrast: 0.5
purpose: []
