analytics:
  google: UA-72243025-1
color:
  brandColors:
    - '#C0E0D8'
    - '#003058'
    - '#608898'
    - '#008BFF'
    - '#000000'
  brandStrength: 0.424549
  lightness: 0.481982
  rhythmicContrast: 0.216216
  saturation: 1
cta: {}
layout_spectrum: 0.421171
name: BenjaminBlue
opengraph: {}
purpose: []
typography_spectrum: 1
