analytics:
  google: UA-72243025-1
color:
  brandColors:
    - '#C8B088'
    - '#000028'
    - '#A86058'
    - '#C06870'
    - '#E0E0A8'
  brandStrength: 0.354729
  lightness: 0.476351
  rhythmicContrast: 0.542792
  saturation: 0
cta: {}
layout_spectrum: 0.796171
name: BenjaminBlue
opengraph: {}
purpose: []
typography_spectrum: 1
