analytics:
  google: UA-47003751-1
color:
  brandColors: []
  brandStrength: 0.25
  lightness: 0.628378
  rhythmicContrast: 0.354729
  saturation: 0.261261
cta: {}
layout_spectrum: 0.18581
name: BenjaminBlue
opengraph: {}
purpose: []
typography_spectrum: 1
